export const ADD_WEATHER = "ADD_WEATHER";
export const SORT_CITIES = "SORT_CITIES";
export const SELECT_CITY = "SELECT_CITY";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_DYNAMICALLY = "FETCH_WEATHER_DYNAMICALLY";
export const CLEAR_WEATHER_LIST = "CLEAR_WEATHER_LIST";
